index:
   path: /
   controller: App\Controller\DefaultController::index

quiz_index:
    path: /quiz
    controller: App\Controller\QuizController::index

scoreboard:
    path: /quiz/scores
    controller: App\Controller\QuizController::score_display


quiz_show:
    path: /quiz/{id}
    controller: App\Controller\QuizController::show_quiz

quiz_question:
    path: /quiz/{id}/{question_num}
    controller: App\Controller\QuizController::show_question

dashboard:
    path: /dashboard
    controller: App\Controller\UserController::dashboard


validation:
    path: /validation/{id}/{token}
    controller: App\Controller\UserController::validation