index:
   path: /
   controller: App\Controller\DefaultController::index

quiz_index:
    path: /quiz
    controller: App\Controller\QuizController::index

quiz_show:
    path: /quiz/{id}
    controller: App\Controller\QuizController::show_quiz

quiz_question:
    path: /quiz/{id}/{question_num}
    controller: App\Controller\QuizController::show_question